replicaCount: 1

image:
  repository: deboraxhx/python-app
  pullPolicy: IfNotPresent
  tag: "v1"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""


podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

livenessProbe: {}
readinessProbe: {}


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
